In [4]:
import numpy as np

In [15]:
# Create the following arrays 
arr1 = np.arange(6).reshape(3,-1)
arr2 = np.arange(3.5, 8.9).reshape(2,-1)
arr3 = np.arange(7,11).reshape(2,-1)

display(arr1,
       arr2,
       arr3)

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[3.5, 4.5, 5.5],
       [6.5, 7.5, 8.5]])

array([[ 7,  8],
       [ 9, 10]])

In [5]:
# Generat a Random array of following shape, and then convert it into 1 D
np.random.seed(55)

a1 = np.random.randint(1,10, [5,3])
display(a1,
       a1.flatten())

array([[8, 9, 6],
       [8, 6, 2],
       [7, 1, 4],
       [9, 8, 2],
       [6, 8, 9]])

array([8, 9, 6, 8, 6, 2, 7, 1, 4, 9, 8, 2, 6, 8, 9])

In [6]:
# get unique elements and their respective counts
x,y = np.unique(a1,return_counts=True)
display(x,'counts',y)

array([1, 2, 4, 6, 7, 8, 9])

'counts'

array([1, 2, 1, 3, 1, 4, 3], dtype=int64)

In [11]:
# Create this list where individual values from the above array have their repective counts
dict(zip(x,y))

{1: 1, 2: 2, 4: 1, 6: 3, 7: 1, 8: 4, 9: 3}

In [7]:
# Get index for maximum value 
np.argmax(x)

6

In [3]:
import numpy as np
x = np.arange(10)
np.where(x%2!=0, -1, x)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])