In [3]:
# Create the following arrays 


array([[0, 1],
       [2, 3],
       [4, 5]])

array([[ 7,  8],
       [ 9, 10]])

In [4]:
# Generat a Random array of following shape, and then convert it into 1 D
np.random.seed(55)


array([[8, 9, 6],
       [8, 6, 2],
       [7, 1, 4],
       [9, 8, 2],
       [6, 8, 9]])

array([8, 9, 6, 8, 6, 2, 7, 1, 4, 9, 8, 2, 6, 8, 9])

In [5]:
# get unique elements and their respective counts from above generated array


array([1, 2, 4, 6, 7, 8, 9])

'counts'

array([1, 2, 1, 3, 1, 4, 3], dtype=int64)

In [6]:
# Create this list where individual values from the above array have their repective counts



{1: 1, 2: 2, 4: 1, 6: 3, 7: 1, 8: 4, 9: 3}

In [7]:
# Get index for maximum value from above array - [1, 2, 4, 6, 7, 8, 9]


6

In [3]:
# generate -1 for odd number and same number when even 


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])